namespace SESport.Core.AI;

public sealed record AiJobRun(
   Guid Id,
   string JobId,
   Guid PromptId,
   int PromptVersion,
   string PromptSystemPrompt,
   string PromptUserPromptTemplate,
   string ProviderId,
   string? ProviderModel,
   AiJobRunStatus Status,
   string? CorrelationId,
   string InputPayloadJson,
   string RenderedPrompt,
   string? RenderedSystemPrompt,
   string RawRequestJson,
   string? RawResponseJson,
   string? ToolTraceJson,
   int ToolRoundCount,
   int ConversationCharacterCount,
   string? OutputText,
   string? ErrorMessage,
   DateTimeOffset StartedAt,
   DateTimeOffset? CompletedAt,
   decimal? DurationSeconds,
   int? InputTokens,
   int? OutputTokens,
   int? ReasoningTokens,
   string ExecutionEnvironment,
   string JobLabel,
   string ProviderLabel,
   string JobOutputMode,
   bool JobRequiresWebSearch,
   string? JobToolsJson,
   string? JobConditionalToolsJson,
   int? JobToolCallMaxTokens,
   string ProviderKind,
   string? ProviderBaseAddress,
   string? ProviderApiKeySource,
   string ProviderRequestOptionsJson,
   string? PromptOutputSchemaJson,
   string PromptRequestOptionsJson,
   decimal? PromptTemperature,
   int? PromptMaxOutputTokens,
   int? PromptMaxToolRounds,
   int MaxOutputTokens,
   int? PromptMinToolRounds = null,
   bool JobIncludeSocialMedia = false,
   string? PromptCodexReasoningEffort = null
);
