<Project Sdk="Microsoft.NET.Sdk.Web">

   <PropertyGroup>
      <TargetFramework>net10.0</TargetFramework>
      <Nullable>enable</Nullable>
      <ImplicitUsings>enable</ImplicitUsings>
      <BuildInParallel>false</BuildInParallel>
      <UseAppHost>false</UseAppHost>
   </PropertyGroup>

   <ItemGroup>
      <ProjectReference Include="..\SESport.Data\SESport.Data.csproj" />
      <ProjectReference Include="..\SESport.AI\SESport.AI.csproj" />
   </ItemGroup>

   <ItemGroup>
      <Content Include="..\..\data\web-stats\*.html">
         <Link>data\web-stats\%(Filename)%(Extension)</Link>
         <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
         <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </Content>
   </ItemGroup>

</Project>
