alter table ai_job_runs
   add column job_label text null,
   add column provider_label text null,
   add column rendered_system_prompt text null,
   add column job_output_mode text null,
   add column job_requires_web_search boolean null,
   add column job_tools_json jsonb null,
   add column job_conditional_tools_json jsonb null,
   add column job_tool_call_max_tokens integer null,
   add column provider_kind text null,
   add column provider_base_address text null,
   add column provider_api_key_source text null,
   add column provider_request_options_json jsonb null,
   add column prompt_output_schema_json jsonb null,
   add column prompt_request_options_json jsonb null,
   add column prompt_temperature numeric(4,2) null,
   add column prompt_max_output_tokens integer null,
   add column prompt_max_tool_rounds integer null;
